### ISSUE TITLE
Translator Recognition

### ISSUE THREAD

**Issue by marc-medley** [nutritionfactsorg/daily-dozen-localization#16]
@salitrov A row for translator recognition has been added to English_US reference TSV. See the key `about_translators` | `info_app_about_translators`.

* [English_US/tsv/English_US_en.app.tsv](https://github.com/nutritionfactsorg/daily-dozen-localization/blob/master/Languages/English_US/tsv/English_US_en.app.tsv)

Please review and update for both text and names. Thanks.

**Comment by marc-medley** [comment]
@salitrov The translator recognition has been provided to the Android Daily Dozen in (Pull Request #211)[https://github.com/nutritionfactsorg/daily-dozen-android/pull/211]. The same list is now in the iPhone version 3.3.3 pending review by Apple to approve for beta testing.

**Comment by marc-medley** [comment]
@salitrov Would it be OK for the Chinese versions of the translation contributors' list to use the international standard ISO 639-1 language codes to identify the language?

* [Wikipedia: List of ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) 

The non-Chinese language translations are (at this point in time) use the ISO codes for the contributor list. The codes allows the list to (1) be more concise with less characters in the screen layout, (2) allows for easier addition of names since the would all be using the same internation standard codes and (3) the part with a name plus code `some name (code)` _does not require any transalation_ be done.

```
Ricard Soler Roger (ca）、 Luděk Bouška (cs）、Lenka Lukacová (cs）、Anke Schliessmann (de）、 …
```

-vs-

```
Ricard Soler Roger（加泰羅尼亞語）、Luděk Bouška（捷克語）、Lenka Lukacová（捷克語）、Anke Schliessmann（德語）、…
```

That said, it is feasible (with some layout rework) to use the translated language names instead of the codes if preferred.

**Comment by salitrov** [comment]
Using the language codes sounds fine to me!

**Comment by marc-medley** [comment]
Updated (zh*) contributor lists to use ISO 639-1 language codes for the next Android & iPhone releases.

**Comment by salitrov** [comment]
Great, thanks Marc!

**Comment by marc-medley** [comment]
The translator contribution item is now released and a standard part of the localization set.
