### ISSUE TITLE
Beans: Metric vs imperial serving size discrepancy

### ISSUE THREAD

**Issue by msiep** [nutritionfactsorg/daily-dozen-localization#29]
The serving size for beans says "1/2 cup cooked beans" for imperial and "130 g cooked beans" for metric. When I weighed 130g of cooked canellini beans it seemed like a very large serving to me, so I tried the imperial measurement. 1/2 a cup of cooked canellini beans weighed 80g, just over half of the metric serving size.  I'm not sure which one is correct, but it clearly needs to be corrected so they're more or less equivalent.

**Comment by marc-medley** [comment]
@msiep This issue has been transfered to the `daily-dozen-localization` repository so that any needed change can be tracked and uniformly applied across the Android app, the iPhone app and the translation team spreadsheets.

**Comment by salitrov** [comment]
I agree and am aware this is an issue. I previously weighed out some hummus and several different types of beans and got these measurements below. Based on this, do you have any suggestions for how we can move forward? I believe our main recommendation is the 1/2 cup cooked beans. It's the metric equivalent we're having trouble with I'd say.

Hummus is ~56 grams per 1/4 cup

**1/2 cup beans**
Black beans, drained, 100g
Kidney beans, drained, 85g
Pinto beans, drained, 90g
Garbanzo beans, drained, 75g

**Comment by msiep** [comment]
If the imperial measurements are correct, then I think the easiest thing to do would be to convert imperial volume measurements such as 1/2 cup into metric volume measurements such as 118 ml. If there are any imperial weight serving sizes such as 1 oz, then convert those into metric weights such as 28 g.

However what I think would be a lot more helpful, though a bigger project, would be to provide weights rather than volumes (for both imperial and metric) except for foods where measuring by volume will reliably give the same result as measuring by weight. 

I find serving sizes such as "1/4 cup Brussels or broccoli sprouts" demotivating since they leave me feeling that I'm half guessing how much I should actually eat. If I have large Brussels sprouts and don't cut them up, I will only be able to fit very few of them into a 1/4 cup, with a great deal of air space around them. If I have small Brussels sprouts and quarter them, then a great deal more of them by weight wil fit in a 1/4 cup, with far less air space. Similarly, how many ounces or grams of cruciferous vegetable I get in "1/2 cup chopped" will vary a lot depending on which vegetable it is and how finely I chop it.

**Comment by salitrov** [comment]
I think something to consider before we dive deeper info specifics and exact measurements is that these are just general recommendations to aim for. Eating approximately these amounts is fine, whether it's a little more or a little less. The general idea is to just be eating these foods regularly. I think considering air space when measuring is getting in the weeds too much, at least for this purpose. We will likely continue on the more simple/accessible path for this reason.

**Comment by msiep** [comment]
I think in this case it would be fine to just consistently use volumes or weights for both metric and imperial, and not take on the bigger project of providing weights for foods where measuring by volume is very approximate. The issue of imprecise volume measurements is present throughout the culture in recipe books, etc., that use volume for things like broccoli florets or brussels sprouts or leafy greens.

However, it's also worth keeping in mind that different people with different personalities and experiences relate differently to imprecise or ambiguous information, and ideally technology and information should be designed to work well for as wide a range of people as is feasible. For some people it can really make a difference to how easy it is to get and stay motivated to do some healthy habit whether the goal is described in a clear and precise way.

**Comment by marc-medley** [comment]
The following would be reasonable to implement:

1) Change the heading to "Serving Sizes (Suggested)". This fits, is unambiguous, and should translate well. 

2) Add a [Frequently Asked Questions](https://nutritionfacts.org/daily-dozen/) section to the application Information menu. Maybe even add a question like "Would the Daily Dozen be considered a portion controlled diet or a lifestyle diet?" to discuss precise measurements vs general guidance.

3) Regarding individual serving weights vs an average serving weight, if the nutrition density is significantly different then add individual lines would make sense to do.   The apps are set up to scale to more lines. It's more a matter of adding the line(s) to spreadsheet and getting the translations to update.

![Servings](https://user-images.githubusercontent.com/15098151/208084377-a78fe497-1a0a-4b9b-811f-95a25e408f5b.png) ![FAQ](https://user-images.githubusercontent.com/15098151/208084382-f64308bc-ef02-43de-9d95-5c8c1f6577b7.png)

**Comment by marc-medley** [comment]
@msiep We are proceeding forward with an update which is broader than the original issue stated here: heading change (all Daily Dozen types), servings review (beans/legumes) and FAQ addition (all Daily Dozen types).  See: ["ChangeSet03: Serving Size (Suggested) & FAQ issue#30"](https://github.com/nutritionfactsorg/daily-dozen-localization/issues/30).

Closing this issue since issue 30 will both address and supercede this issue. Thanks for bringing the serving size discrepancy to our attention.
