### ISSUE TITLE
Catalan: translation proposal

### ISSUE THREAD

**Issue by jowis** [nutritionfactsorg/daily-dozen-localization#5]
Can I translate Daily Dozen into Catalan?

**Comment by marc-medley** [comment]
@jowis  The translation process has now evolved such that an online application is available for anyone interested to be part of the internal _Daily Dozen App Translation Volunteer Team_ which works with Steven Litrov (@salitrov) the Global Volunteer Director:

* [https://nutritionfacts.org/volunteer/app-translation-volunteer/](https://nutritionfacts.org/volunteer/app-translation-volunteer/)

You are welcome to apply. And yes, we are currently in needed of some Catalan translation talent.

Thank you for your patience with the Daily Dozen App Translation process evolution.

--Marc

**Comment by marc-medley** [comment]
@jowis The [Daily Dozen App Translation Volunteer online application](https://nutritionfacts.org/volunteer/app-translation-volunteer/) link is now generally referenced in Issue https://github.com/nutritionfactsorg/daily-dozen-localization/issues/24.
